openapi: 3.0.1
info:
  title: Reusable - 可复用代码
  description: Reusable API文档
  contact:
    name: Luke Xie
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: v1.0.0
servers:
  - url: http://localhost:1000
    description: Generated server url
paths:
  /files:
    post:
      tags:
        - API - 文件处理
      summary: 解析并返回文件内容
      description: 上传文件并使用Apache Tika解析文件内容<br>支持解析：doc、docx、ppt、pptx、xls、xlsx、pdf、txt、md、xml、json、html、css、js、java、sql、properties、ini、yaml、yml等文件
      operationId: parseFileContent
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /excels:
    get:
      tags:
        - API - Excel
      summary: 导出
      description: 查询数据后直接导出<br>流程：查询数据 - 构造Excel文件 - 导出Excel
      operationId: export
      responses:
        "200":
          description: OK
components: {}
x-openapi:
  x-setting:
    customCode: 200
    language: zh-CN
    enableSwaggerModels: true
    swaggerModelName: Swagger Models
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableDocumentManage: true
    enableVersion: false
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    enableHost: false
    enableHostText: ""
    enableDynamicParameter: false
    enableDebug: true
    enableFooter: true
    enableFooterCustom: false
    enableSearch: true
    enableOpenApi: true
    enableHomeCustom: false
    enableGroup: true
    enableResponseCode: true
  x-markdownFiles: []
